version: '3.8'

services:
  web:
    build:
      context: ./Lofocam
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Lofocam:/var/www/html
    depends_on:
      - db
    networks:
      - lofocam-network

  db:
    build:
      context: ./db-lofocam
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: lofocam
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lofocam-network

volumes:
  db_data:

networks:
  lofocam-network:
    driver: bridge
